Repository bolmal/Back-end, pull requests merged in 2025-02, with the labels that each got.

#4 [feat] 회원 CRUD 구현
  .gitignore
  src/main/java/com/example/bolmalre/BolmalReApplication.java
  src/main/java/com/example/bolmalre/auth/filter/LoginFilter.java
  src/main/java/com/example/bolmalre/auth/jwt/JWTFilter.java
  src/main/java/com/example/bolmalre/auth/service/CustomUserDetailsService.java
  src/main/java/com/example/bolmalre/auth/web/dto/CustomUserDetails.java
  src/main/java/com/example/bolmalre/common/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/com/example/bolmalre/config/SecurityConfig.java
  src/main/java/com/example/bolmalre/member/AgreementRepository.java
  src/main/java/com/example/bolmalre/member/MemberController.java
  src/main/java/com/example/bolmalre/member/MemberRepository.java
  src/main/java/com/example/bolmalre/member/MemberService.java
  src/main/java/com/example/bolmalre/member/MemberServiceImpl.java
  src/main/java/com/example/bolmalre/member/converter/MemberConverter.java
  src/main/java/com/example/bolmalre/member/domain/Agreement.java
  src/main/java/com/example/bolmalre/member/domain/Member.java
  src/main/java/com/example/bolmalre/member/domain/enums/Gender.java
  src/main/java/com/example/bolmalre/member/domain/enums/Role.java
  src/main/java/com/example/bolmalre/member/domain/enums/Status.java
  src/main/java/com/example/bolmalre/member/domain/enums/SubStatus.java
  src/main/java/com/example/bolmalre/member/enums/Gender.java
  src/main/java/com/example/bolmalre/member/enums/Role.java
  src/main/java/com/example/bolmalre/member/enums/Status.java
  src/main/java/com/example/bolmalre/member/infrastructure/AgreementRepository.java
  src/main/java/com/example/bolmalre/member/infrastructure/LocalDateHolder.java
  src/main/java/com/example/bolmalre/member/infrastructure/LocalDateHolderImpl.java
  src/main/java/com/example/bolmalre/member/infrastructure/MemberRepository.java
  src/main/java/com/example/bolmalre/member/service/MemberServiceImpl.java
  src/main/java/com/example/bolmalre/member/validation/annotation/PasswordPatternValid.java
  src/main/java/com/example/bolmalre/member/validation/annotation/PhoneNumberValid.java
  src/main/java/com/example/bolmalre/member/validation/annotation/UsernameDuplicate.java
  src/main/java/com/example/bolmalre/member/validation/annotation/UsernamePatternValid.java
  src/main/java/com/example/bolmalre/member/validation/validator/PasswordPatternValidator.java
  src/main/java/com/example/bolmalre/member/validation/validator/PhoneNumberValidator.java
  src/main/java/com/example/bolmalre/member/validation/validator/UsernameDuplicateValidator.java
  src/main/java/com/example/bolmalre/member/validation/validator/UsernamePatternValidator.java
  src/main/java/com/example/bolmalre/member/web/controller/MemberController.java
  src/main/java/com/example/bolmalre/member/web/dto/MemberFindPasswordDTO.java
  src/main/java/com/example/bolmalre/member/web/dto/MemberFindUsernameDTO.java
  src/main/java/com/example/bolmalre/member/web/dto/MemberJoinDTO.java
  src/main/java/com/example/bolmalre/member/web/dto/MemberPasswordValidDTO.java
  src/main/java/com/example/bolmalre/member/web/dto/MemberProfileDTO.java
  src/main/java/com/example/bolmalre/member/web/dto/MemberUpdateDTO.java
  src/main/java/com/example/bolmalre/member/web/port/MemberService.java
  src/main/resources/application.yml
  src/test/java/com/example/bolmalre/BolmalReApplicationTests.java
  src/test/java/com/example/bolmalre/member/service/MemberServiceImplTest.java
  src/test/java/com/example/bolmalre/member/web/dto/MemberFindPasswordDTOTest.java
  src/test/java/com/example/bolmalre/member/web/dto/MemberFindUsernameDTOTest.java
  src/test/java/com/example/bolmalre/member/web/dto/MemberJoinDTOTest.java
  src/test/java/com/example/bolmalre/member/web/dto/MemberPasswordValidDTOTest.java
  src/test/java/com/example/bolmalre/member/web/dto/MemberUpdateDTOTest.java
Labels: :sparkles: feat, :test_tube: test

#13 [feat] 알림 & 찜 핵심로직 구현
  src/main/java/com/example/bolmalre/alarm/converter/AlarmConverter.java
  src/main/java/com/example/bolmalre/alarm/infrastructure/AlarmRepository.java
  src/main/java/com/example/bolmalre/alarm/service/AlarmServiceImpl.java
  src/main/java/com/example/bolmalre/alarm/util/AlarmMailUtil.java
  src/main/java/com/example/bolmalre/alarm/web/controller/AlarmController.java
  src/main/java/com/example/bolmalre/alarm/web/dto/AlarmReadDTO.java
  src/main/java/com/example/bolmalre/alarm/web/port/AlarmService.java
  src/main/java/com/example/bolmalre/artist/domain/Artist.java
  src/main/java/com/example/bolmalre/artist/infrastructure/ArtistRepository.java
  src/main/java/com/example/bolmalre/bookmark/converter/BookmarkConverter.java
  src/main/java/com/example/bolmalre/bookmark/infrastructure/BookmarkRepository.java
  src/main/java/com/example/bolmalre/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/example/bolmalre/bookmark/util/BookmarkMailUtil.java
  src/main/java/com/example/bolmalre/bookmark/web/controller/BookmarkController.java
  src/main/java/com/example/bolmalre/bookmark/web/dto/BookmarkGetArtistDTO.java
  src/main/java/com/example/bolmalre/bookmark/web/dto/BookmarkRegisterDTO.java
  src/main/java/com/example/bolmalre/bookmark/web/port/BookmarkService.java
  src/main/java/com/example/bolmalre/common/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/com/example/bolmalre/common/apiPayLoad/exception/handler/AlarmHandler.java
  src/main/java/com/example/bolmalre/common/apiPayLoad/exception/handler/BookmarkHandler.java
  src/main/java/com/example/bolmalre/common/apiPayLoad/exception/handler/ConcertHandler.java
  src/main/java/com/example/bolmalre/concert/converter/ConcertArtistTempConverter.java
  src/main/java/com/example/bolmalre/concert/converter/ConcertTempConverter.java
  src/main/java/com/example/bolmalre/concert/infrastructure/ConcertArtistRepository.java
  src/main/java/com/example/bolmalre/concert/infrastructure/ConcertRepository.java
  src/main/java/com/example/bolmalre/concert/service/ConcertTempService.java
  src/main/java/com/example/bolmalre/concert/web/controller/ConcertTempController.java
  src/main/java/com/example/bolmalre/concert/web/dto/SaveDTO.java
  src/main/java/com/example/bolmalre/member/domain/Member.java
  src/main/java/com/example/bolmalre/member/web/controller/MemberImageController.java
  src/main/resources/templates/alarm.html
  src/main/resources/templates/bookmark.html
  src/test/java/com/example/bolmalre/alarm/service/AlarmServiceImplTest.java
  src/test/java/com/example/bolmalre/alarm/util/AlarmMailUtilTest.java
  src/test/java/com/example/bolmalre/bookmark/service/BookmarkServiceImplTest.java
  src/test/java/com/example/bolmalre/bookmark/util/BookmarkAlarmUtilTest.java
  src/test/java/com/example/bolmalre/concert/infrastructure/ConcertRepositoryTest.java
  src/test/java/com/example/bolmalre/member/infrastructure/MemberRepositoryTest.java
Labels: :sparkles: feat

#14 [feat] 콘서트 로직 및 엔티티 리팩터링
  src/main/java/com/example/bolmalre/alarm/converter/AlarmConverter.java
  src/main/java/com/example/bolmalre/alarm/util/AlarmMailUtil.java
  src/main/java/com/example/bolmalre/alarm/web/dto/AlarmReadDTO.java
  src/main/java/com/example/bolmalre/concert/converter/ConcertConverter.java
  src/main/java/com/example/bolmalre/concert/converter/ConcertTempConverter.java
  src/main/java/com/example/bolmalre/concert/domain/Concert.java
  src/main/java/com/example/bolmalre/concert/domain/ConcertImage.java
  src/main/java/com/example/bolmalre/concert/domain/ConcertPerformanceRound.java
  src/main/java/com/example/bolmalre/concert/domain/ConcertPrice.java
  src/main/java/com/example/bolmalre/concert/domain/ConcertRecommend.java
  src/main/java/com/example/bolmalre/concert/domain/ConcertTicketRound.java
  src/main/java/com/example/bolmalre/concert/domain/enums/TicketRound.java
  src/main/java/com/example/bolmalre/concert/infrastructure/ConcertImageRepository.java
  src/main/java/com/example/bolmalre/concert/infrastructure/ConcertPerformanceRoundRepository.java
  src/main/java/com/example/bolmalre/concert/infrastructure/ConcertPriceRepository.java
  src/main/java/com/example/bolmalre/concert/infrastructure/ConcertRecommendRepository.java
  src/main/java/com/example/bolmalre/concert/infrastructure/ConcertRepository.java
  src/main/java/com/example/bolmalre/concert/infrastructure/ConcertTicketRoundRepository.java
  src/main/java/com/example/bolmalre/concert/service/ConcertImageServiceImpl.java
  src/main/java/com/example/bolmalre/concert/service/ConcertServiceImpl.java
  src/main/java/com/example/bolmalre/concert/web/controller/ConcertController.java
  src/main/java/com/example/bolmalre/concert/web/controller/ConcertImageController.java
  src/main/java/com/example/bolmalre/concert/web/dto/ConcertDetailPageDTO.java
  src/main/java/com/example/bolmalre/concert/web/dto/ConcertHomeDTO.java
  src/main/java/com/example/bolmalre/concert/web/dto/ConcertPageDTO.java
  src/main/java/com/example/bolmalre/concert/web/dto/SaveDTO.java
  src/main/java/com/example/bolmalre/concert/web/port/ConcertImageService.java
  src/main/java/com/example/bolmalre/concert/web/port/ConcertService.java
  src/main/resources/application.yml
  src/test/java/com/example/bolmalre/alarm/service/AlarmServiceImplTest.java
  src/test/java/com/example/bolmalre/concert/ConcertServiceImplTest.java
  src/test/java/com/example/bolmalre/concert/infrastructure/ConcertRepositoryTest.java
Labels: :chains: refactor, :sparkles: feat

#18 [fix] 테스트 코드 변동사항 수정
  src/main/java/com/example/bolmalre/alarm/util/AlarmMailUtil.java
  src/main/java/com/example/bolmalre/concert/domain/Concert.java
  src/main/java/com/example/bolmalre/concert/infrastructure/ConcertRepository.java
  src/test/java/com/example/bolmalre/alarm/service/AlarmServiceImplTest.java
  src/test/java/com/example/bolmalre/alarm/util/AlarmMailUtilTest.java
  src/test/java/com/example/bolmalre/concert/infrastructure/ConcertRepositoryTest.java
Labels: :wrench: fix

#20 [feat] 카카오 소셜로그인 구현
  build.gradle
  src/main/java/com/example/bolmalre/auth/filter/CustomLogoutFilter.java
  src/main/java/com/example/bolmalre/auth/filter/LoginFilter.java
  src/main/java/com/example/bolmalre/common/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/com/example/bolmalre/config/RestTemplateConfig.java
  src/main/java/com/example/bolmalre/config/SecurityConfig.java
  src/main/java/com/example/bolmalre/member/converter/MemberConverter.java
  src/main/java/com/example/bolmalre/member/infrastructure/MemberRepository.java
  src/main/java/com/example/bolmalre/member/infrastructure/UuidHolder.java
  src/main/java/com/example/bolmalre/member/infrastructure/UuidHolderImpl.java
  src/main/java/com/example/bolmalre/member/service/OAuthServiceImpl.java
  src/main/java/com/example/bolmalre/member/util/CookieUtil.java
  src/main/java/com/example/bolmalre/member/util/KakaoUtil.java
  src/main/java/com/example/bolmalre/member/web/controller/MemberOAuthController.java
  src/main/java/com/example/bolmalre/member/web/dto/KakaoDTO.java
  src/main/java/com/example/bolmalre/member/web/port/OAuthService.java
  src/main/resources/application.yml
Labels: :sparkles: feat

#23 [feat] API 구현
  src/main/java/com/example/bolmalre/member/service/MemberServiceImpl.java
  src/main/java/com/example/bolmalre/member/web/controller/MemberController.java
  src/main/java/com/example/bolmalre/member/web/dto/MemberJoinDTO.java
  src/main/java/com/example/bolmalre/member/web/port/MemberService.java
Labels: :sparkles: feat

#25 [feat] 프론트 네이버 소셜로그인 API 수정
  src/main/java/com/example/bolmalre/member/converter/MemberConverter.java
  src/main/java/com/example/bolmalre/member/service/MemberServiceImpl.java
  src/main/java/com/example/bolmalre/member/service/OAuthServiceImpl.java
  src/main/java/com/example/bolmalre/member/web/controller/MemberController.java
  src/main/java/com/example/bolmalre/member/web/controller/MemberOAuthController.java
  src/main/java/com/example/bolmalre/member/web/port/MemberService.java
  src/main/java/com/example/bolmalre/member/web/port/OAuthService.java
Labels: :sparkles: feat

#27 [feat] 네이버 소셜로그인 구현
  build.gradle
  src/main/java/com/example/bolmalre/config/SecurityConfig.java
  src/main/java/com/example/bolmalre/member/converter/MemberConverter.java
  src/main/java/com/example/bolmalre/member/domain/Member.java
  src/main/java/com/example/bolmalre/member/oauth/CustomOAuth2User.java
  src/main/java/com/example/bolmalre/member/oauth/CustomOAuth2UserService.java
  src/main/java/com/example/bolmalre/member/oauth/CustomSuccessHandler.java
  src/main/java/com/example/bolmalre/member/oauth/NaverResponse.java
  src/main/java/com/example/bolmalre/member/oauth/OAuth2Response.java
  src/main/java/com/example/bolmalre/member/service/OAuthServiceImpl.java
  src/main/java/com/example/bolmalre/member/util/NaverUtil.java
  src/main/java/com/example/bolmalre/member/web/controller/MemberOAuthController.java
  src/main/java/com/example/bolmalre/member/web/controller/MemberOAuthSSRController.java
  src/main/java/com/example/bolmalre/member/web/dto/MemberJoinDTO.java
  src/main/java/com/example/bolmalre/member/web/dto/NaverDTO.java
  src/main/java/com/example/bolmalre/member/web/port/OAuthService.java
  src/main/resources/application.yml
  src/main/resources/templates/oauth/login.html
  src/main/resources/templates/oauth/success.html
Labels: :sparkles: feat

#29 [chore] 로그인 로직 기능 수정
  src/main/java/com/example/bolmalre/auth/filter/CustomLogoutFilter.java
  src/main/java/com/example/bolmalre/auth/filter/LoginFilter.java
  src/main/java/com/example/bolmalre/auth/infrastructure/port/RefreshRedisEntity.java
  src/main/java/com/example/bolmalre/auth/infrastructure/redis/RefreshRedisRepository.java
  src/main/java/com/example/bolmalre/auth/infrastructure/redis/RefreshRedisRepositoryImpl.java
  src/main/java/com/example/bolmalre/auth/infrastructure/redis/RefreshRepository.java
  src/main/java/com/example/bolmalre/auth/service/RefreshTokenService.java
  src/main/java/com/example/bolmalre/auth/service/port/RefreshRepository.java
  src/main/java/com/example/bolmalre/auth/web/controller/ReissueController.java
  src/main/java/com/example/bolmalre/config/SecurityConfig.java
  src/main/java/com/example/bolmalre/member/converter/MemberConverter.java
  src/main/java/com/example/bolmalre/member/domain/Member.java
  src/main/java/com/example/bolmalre/member/web/controller/MemberController.java
Labels: :pencil2: chore

#33 [test] 자코코 도입 및 MemberController 통합 테스트 구현
  build.gradle
  src/test/java/com/example/bolmalre/member/web/controller/MemberControllerTest.java
Labels: :sparkles: feat, :test_tube: test

#34 [chore] BCrypt 추상화
  src/main/java/com/example/bolmalre/member/converter/MemberConverter.java
  src/main/java/com/example/bolmalre/member/infrastructure/BCryptHolderImpl.java
  src/main/java/com/example/bolmalre/member/infrastructure/LocalDateHolderImpl.java
  src/main/java/com/example/bolmalre/member/service/MemberServiceImpl.java
  src/main/java/com/example/bolmalre/member/service/OAuthServiceImpl.java
  src/main/java/com/example/bolmalre/member/service/port/BCryptHolder.java
  src/test/java/com/example/bolmalre/member/infrastructure/BCryptHolderImplTest.java
  src/test/java/com/example/bolmalre/member/service/MemberServiceImplTest.java
  src/test/java/com/example/bolmalre/member/web/controller/MemberControllerTest.java
Labels: :pencil2: chore

#38 [FEATURE] 메인페이지 API 구현 및 리팩터링 #37
  src/main/java/com/example/bolmalre/concert/converter/ConcertConverter.java
  src/main/java/com/example/bolmalre/concert/domain/Concert.java
  src/main/java/com/example/bolmalre/concert/infrastructure/ConcertPerformanceRoundRepository.java
  src/main/java/com/example/bolmalre/concert/infrastructure/ConcertRepository.java
  src/main/java/com/example/bolmalre/concert/infrastructure/ConcertTicketRoundRepository.java
  src/main/java/com/example/bolmalre/concert/service/ConcertServiceImpl.java
  src/main/java/com/example/bolmalre/concert/web/controller/ConcertController.java
  src/main/java/com/example/bolmalre/concert/web/dto/ConcertHomeDTO.java
  src/main/java/com/example/bolmalre/config/SecurityConfig.java
Labels: :chains: refactor, :sparkles: feat

#42 [fix] 로그인 실패 응답 수정
  src/main/java/com/example/bolmalre/auth/filter/LoginFilter.java
Labels: :wrench: fix

#43 [REFACTOR] 서비스 메소드 단일 책임 원칙 #40
  src/main/java/com/example/bolmalre/concert/converter/ConcertConverter.java
  src/main/java/com/example/bolmalre/concert/converter/ConcertDtoConverter.java
  src/main/java/com/example/bolmalre/concert/converter/SaveConcertConverter.java
  src/main/java/com/example/bolmalre/concert/infrastructure/ConcertPriceRepository.java
  src/main/java/com/example/bolmalre/concert/infrastructure/ConcertRepository.java
  src/main/java/com/example/bolmalre/concert/infrastructure/ConcertTicketRoundRepository.java
  src/main/java/com/example/bolmalre/concert/service/ConcertServiceImpl.java
  src/main/java/com/example/bolmalre/concert/service/SaveConcertService.java
  src/main/java/com/example/bolmalre/concert/web/controller/ConcertController.java
  src/main/java/com/example/bolmalre/concert/web/controller/HomeConcertController.java
  src/main/java/com/example/bolmalre/concert/web/controller/SaveConcertController.java
  src/main/java/com/example/bolmalre/concert/web/dto/ConcertDetailPageDTO.java
  src/main/java/com/example/bolmalre/concert/web/dto/ConcertHomeDTO.java
  src/main/java/com/example/bolmalre/concert/web/port/ConcertService.java
  src/main/java/com/example/bolmalre/config/SecurityConfig.java
Labels: :chains: refactor, :sparkles: feat

#45 [FEATURE] 콘서트 페이지 API #44
  src/main/java/com/example/bolmalre/common/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/com/example/bolmalre/concert/converter/ConcertConverter.java
  src/main/java/com/example/bolmalre/concert/converter/ConcertDtoConverter.java
  src/main/java/com/example/bolmalre/concert/domain/enums/SortType.java
  src/main/java/com/example/bolmalre/concert/infrastructure/ConcertRepository.java
  src/main/java/com/example/bolmalre/concert/infrastructure/ConcertTicketRoundRepository.java
  src/main/java/com/example/bolmalre/concert/service/ConcertServiceImpl.java
  src/main/java/com/example/bolmalre/concert/web/controller/ConcertController.java
  src/main/java/com/example/bolmalre/concert/web/dto/ConcertHomeDTO.java
  src/main/java/com/example/bolmalre/concert/web/dto/ConcertPageDTO.java
  src/main/java/com/example/bolmalre/concert/web/port/ConcertService.java
Labels: :chains: refactor, :sparkles: feat, :wrench: fix
